server:
  port: 9998

spring:
  application:
    name: langchain4j
langchain4j:
  ollama:
    chat-model:
      model-name: qwen2:latest
      base-url: http://192.168.0.:11434
      top-k: 5
      top-p:  0.9
      temperature: 0.4
    streaming-chat-model:
      model-name: qwen2:latest
      base-url: http://192.168.0.:11434
      top-k: 5
      top-p: 0.9
      temperature: 0.4
    embedding-model:
      model-name: nomic-embed-text:latest
      base-url: http://192.168.0.:11434
  store:
    redis:
      host: localhost
      port: 6379
      password: redis
      database: 0
      max_connections: 10
  embeddingstore:
      redis:
        host: localhost
        port: 6379
        password:
