server:
  port: 9998

spring:
  application:
    name: langchain4j
langchain4j:
  ollama:
    chat-model:
      model-name: qwen:0.5b
      base-url: http://192.168.0.26:11434
      top-k: 5
      top-p:  0.9
      temperature: 0.4
    streaming-chat-model:
      model-name: qwen:0.5b
      base-url: http://192.168.0.26:11434
      top-k: 5
      top-p: 0.9
      temperature: 0.4
    embedding-model:
      model-name: mofanke/dmeta-embedding-zh:latest
      base-url: http://192.168.0.26:11434
