server:
  port: 9999

spring:
  application:
    name: chat-ollama
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen:0.5b
      embedding:
        options:
          model: mofanke/dmeta-embedding-zh:latest
    vectorstore:
      redis:
        uri: http://127.0.0.1:6379
        index: chat-ollama
        initialize-schema: true
        prefix: chat-ollama