###
GET http://localhost:9999/springaiChat/message2?message=我是victor
Accept: application/json

###
GET http://localhost:9999/springaiChat/message?message=我是谁
Accept: application/json

###
POST http://localhost:9999/springaiChat/message?message=我是谁
Content-Type:application/x-www-form-urlencoded
Accept: application/json



